# Generated by Django 3.1.7 on 2021-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=120)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
