# Generated by Django 3.1.7 on 2021-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
